import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from './components/NavBar'
import Map from './components/Map'
import TextInput from './components/TextInput'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        
        <span> Test here or below... </span>
        <TextInput/>
        <Map lat={ 42.454323} lng={ -76.475266}/>
      </main>
    </>
  )
}
